#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Generate a styled index.html for GitHub Pages
# Usage: generate-index.sh <pages-directory>

set -euo pipefail

PAGES_DIR="${1:?Usage: generate-index.sh <pages-directory>}"

cat > "${PAGES_DIR}/index.html" << 'OUTER_EOF'
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>ONAP Release Mapping</title>
  <style>
    :root {
      --bg: #0d1117; --fg: #c9d1d9; --card-bg: #161b22;
      --border: #30363d; --accent: #58a6ff; --green: #3fb950;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI",
                   Helvetica, Arial, sans-serif;
      background: var(--bg); color: var(--fg);
      max-width: 960px; margin: 0 auto; padding: 2rem 1rem;
    }
    h1 { color: var(--accent); margin-bottom: 0.5rem; }
    .subtitle { color: #8b949e; margin-bottom: 2rem; }
    .cards { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 1rem; }
    .card {
      background: var(--card-bg); border: 1px solid var(--border);
      border-radius: 6px; padding: 1.25rem;
      transition: border-color 0.2s;
    }
    .card:hover { border-color: var(--accent); }
    .card h3 { color: var(--accent); margin-bottom: 0.5rem; }
    .card a {
      color: var(--accent); text-decoration: none;
      display: inline-block; margin: 0.25rem 0.5rem 0.25rem 0;
    }
    .card a:hover { text-decoration: underline; }
    .badge {
      display: inline-block; font-size: 0.75rem; padding: 0.15rem 0.5rem;
      border-radius: 1rem; background: var(--green); color: #000;
      font-weight: 600;
    }
    footer { margin-top: 3rem; color: #8b949e; font-size: 0.85rem; }
  </style>
</head>
<body>
  <h1>ONAP Release Mapping</h1>
  <p class="subtitle">Historical release component manifests</p>
  <div class="cards">
    <div class="card">
      <h3>Latest <span class="badge">current</span></h3>
      <p>Most recent mapping run</p>
      <a href="latest/manifest.json">JSON</a>
      <a href="latest/manifest.md">Markdown</a>
      <a href="latest/manifest.yaml">YAML</a>
      <a href="latest/manifest.csv">CSV</a>
    </div>
OUTER_EOF

# Add a card for each date-stamped directory (newest first)
for dir in $(find "${PAGES_DIR}" -maxdepth 1 -type d -name '2*' | sort -r); do
  DATE=$(basename "$dir")
  cat >> "${PAGES_DIR}/index.html" << EOF
    <div class="card">
      <h3>${DATE}</h3>
      <a href="${DATE}/manifest.json">JSON</a>
      <a href="${DATE}/manifest.md">Markdown</a>
      <a href="${DATE}/manifest.yaml">YAML</a>
      <a href="${DATE}/manifest.csv">CSV</a>
    </div>
EOF
done

cat >> "${PAGES_DIR}/index.html" << 'OUTER_EOF'
  </div>
  <footer>
    <p>Generated by
      <a href="https://github.com/modeseven-lfit/onap-release-mapping-tool">
        onap-release-mapping-tool
      </a>
    </p>
  </footer>
</body>
</html>
OUTER_EOF

echo "Generated index.html in ${PAGES_DIR}"
