version = 1

# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

[[annotations]]
path = [
    "tests/fixtures/**",
    "*.lock",
    "docs/*.png",
    "**/__pycache__/**",
    ".secrets.**",
    "src/onap_release_map/schemas/*.json"
]
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileCopyrightText = "2025 The Linux Foundation"
